name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [dell-windows-11, hp-windows-10]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set PowerShell Execution Policy
      shell: powershell
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force

      
    # - name: Enable Developer Mode
    #   shell: powershell
    #   run: |
    #     reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /t REG_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1"
        
    # - name: Install WinAppDriver
    #   shell: powershell
    #   run: |
    #     $winAppDriverUrl = "https://github.com/microsoft/WinAppDriver/releases/download/v1.2.1/WindowsApplicationDriver_1.2.1.msi"
    #     $installerPath = "$env:TEMP\WinAppDriver.msi"
    #     Invoke-WebRequest -Uri $winAppDriverUrl -OutFile $installerPath
    #     Start-Process msiexec.exe -ArgumentList "/i $installerPath /quiet /qn" -Wait
        
    #     # Verify installation
    #     if (Test-Path "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe") {
    #       Write-Host "WinAppDriver installed successfully in Program Files (x86)"
    #     } elseif (Test-Path "C:\Program Files\Windows Application Driver\WinAppDriver.exe") {
    #       Write-Host "WinAppDriver installed successfully in Program Files"
    #     } else {
    #       Write-Host "WinAppDriver installation may have failed. Checking installation logs..."
    #       Get-Content "$env:TEMP\msi*.log" -ErrorAction SilentlyContinue | Select-String "WinAppDriver"
    #       throw "WinAppDriver not found after installation"
    #     }
      
    - name: Start WinAppDriver
      shell: powershell
      run: |
        # Try both possible installation paths
        if (Test-Path "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe") {
          Start-Process "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"
        } elseif (Test-Path "C:\Program Files\Windows Application Driver\WinAppDriver.exe") {
          Start-Process "C:\Program Files\Windows Application Driver\WinAppDriver.exe"
        } else {
          Write-Host "WinAppDriver not found in expected locations. Checking installation..."
          Get-ChildItem "C:\Program Files" -Recurse -Filter "WinAppDriver.exe" -ErrorAction SilentlyContinue
          Get-ChildItem "C:\Program Files (x86)" -Recurse -Filter "WinAppDriver.exe" -ErrorAction SilentlyContinue
          throw "WinAppDriver not found"
        }
        Start-Sleep -s 5
        
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v4.0
      with:
          version: '9.7.4'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType=Windows -statusDelay=15 -testSuitePath="Test Suites/SampleTestSuite" -apiKey="37d7a759-1bad-43a1-b9c6-19f64534178d"'
